services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5173:5173
    environment:
      - VITE_WORDLEASSIST_API_URL=http://localhost:7071/api/WordleAssist
    restart: unless-stopped